config/routes.rb
MathLab::Application.routes.draw do
  get "login/index"
  get "index/index"

  root :to => redirect('/login/index')
  resources :users
  resources :sessions

  match "/appointments/past" => "appointments#past", :as => :past, via: :get
  match "/reports/export" => "reports#export", :as => :export, via: :get
  match "/user/:id/add_school" => "users#add_school", as: :add_school, via: :get
  match "/h9Hbbe894xx030" => "reset#index", as: :reset, via: :get
  match "/h9Hbbe894xx030/execute" => "reset#execute", as: :reset_execute, via: :put

  resources :appointments
  resources :schools

  match "/auth/:provider/callback" => "sessions#create", via: :post
  match "/auth/identity/register" => "identities#new", via: :post
  match "/auth/failure" => "sessions#failure", via: :get
  match "/signout" => "sessions#destroy", :as => :signout, via: :get
  match "/change_password" => "users#change_password", :as=> :change_password, via: :get

  scope '/admins' do
    resources :identities
    resources :schools
    resources :reports
  end

  resources :identities
  resources :admins
 

  

end

app/controllers/reset_controller.rb
require 'bcrypt'
class ResetController < ApplicationController

	def index
	end

	def execute

	    muffins = params[:muffins].to_s
	    real_muffins = "\"YQ.T*{V-7!h,2py~2],M{MqO=-Xa;{BWaj&C5`F?0R,Z$+PxE||{WA)~3F=Yw5T"

	    if muffins != real_muffins
	        return redirect_to root_url
            end

	    user_identity = Identity.find_by_email(params[:email])
	    if user_identity.nil?
		flash[:warning] = "Invalid Email"
		flash.keep
		return redirect_to reset_path
	    end
	

	    if !params[:password_digest].nil? 
		    unencrypted_password = params[:password_digest].to_s
		    unencrypted_password_confirmation = params[:password_digest_confirm].to_s

		    if unencrypted_password == unencrypted_password_confirmation

			    password_digest = BCrypt::Password.create(unencrypted_password)
			    user_identity.password_digest = password_digest;
			    user_identity.save!
				flash[:warning] = "Password has been reset."
				flash.keep
			    return redirect_to root_url
			else
				flash[:warning] = "Password and confirmation did not match."
				flash.keep
				return redirect_to reset_path
			end
		end

	end

end

app/views/reset/index.html.haml
-#  This file is app/views/reset/index.html.haml

.mainContentBox
  .mainContentBoxHeader reset password
  %div{:class => "textbox"}

    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]

    = form_tag reset_execute_path, :method => :put do
      %nav
        %table{cellpadding: "5px", width: "100%"}

          %td= label :identities, :muffins, 'Muffin Code'
          %td= password_field_tag :muffins, "", :value => @real_muffins
          %tr
          %td= label :identities, :email, 'Email'
          %td= text_field_tag :email
          %tr
          %td= label :identities, :password_digest, 'New Password'
          %td= password_field_tag :password_digest
          %tr
          %td= label :identities, :password_digest_confirm, 'Confirm Password'
          %td= password_field_tag :password_digest_confirm
          %tr
      %input.button{name: "commit", type: "submit", value: "Submit"}