config/routes.rb
MathLab::Application.routes.draw do
  get "login/index"
  get "index/index"

  root :to => redirect('/login/index')
  resources :users
  resources :sessions

  match "/appointments/past" => "appointments#past", :as => :past, via: :get
  match "/reports/export" => "reports#export", :as => :export, via: :get
  match "/user/:id/add_school" => "users#add_school", as: :add_school, via: :get
  match "/h9Hbbe894xx030" => "reset#index", as: :reset, via: :get
  match "/h9Hbbe894xx030/execute" => "reset#execute", as: :reset_execute, via: :put

  resources :appointments
  resources :schools

  match "/auth/:provider/callback" => "sessions#create", via: :post
  match "/auth/identity/register" => "identities#new", via: :post
  match "/auth/failure" => "sessions#failure", via: :get
  match "/signout" => "sessions#destroy", :as => :signout, via: :get
  match "/change_password" => "users#change_password", :as=> :change_password, via: :get

  scope '/admins' do
    resources :identities
    resources :schools
    resources :reports
  end

  resources :identities
  resources :admins
 

  

end

app/models/identity.rb
class Identity < OmniAuth::Identity::Models::ActiveRecord
	belongs_to :user
	validates_presence_of :password, on: :create
	validates_presence_of :name
	validates_uniqueness_of :email
	validates_format_of :email, :with => /\A[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}\z/i
end

app/controllers/identities_controller.rb
class IdentitiesController < AdminsController

	def new
   		#@schools = []
    		#School.all.each do |school|
      		#	@schools << school.name
    		#end
		@identity = env['omniauth.identity']
	end

	def index
	    @all_users = User::USER_TYPES
	    @selected_users = params[:user_types] || session[:user_types] || {}

	    if @selected_users == {}
	      @selected_users = Hash[@all_users.map {|user| [user, user]}]
	    end
    
	    if params[:user_types] != session[:user_types]
	      session[:user_types] = @selected_users
	      redirect_to :user_types => @selected_users and return
	    end
    	# @users = User.find_all_by_rank(@selected_users.keys) 
	    @users = User.paginate(:page => params[:page], :per_page => 10).find_all_by_rank(@selected_users.keys) 


    end

	def create
		@identity = Identity.new(params[:identity].permit(:rank, :name, :email, :password, :password_confirmation))
		  
		@identity.save
		flash[:alert] = "You have successfully made an account!"
		redirect_to "/admins"	
	end
	def show
		@user = User.find_by_uid(params[:id])
		@identity = Identity.find_by_email(@user.email)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:notice] = "User '#{@user.name}' had been deleted."
		redirect_to users_path
	end

end

app/helpers/identities_helper.rb
module IdentitiesHelper
end

app/views/identities/index.html.haml
%h2 All Users

%p
  =link_to "Create New Accounts", "identities/new"


  
  / = link_to 'Refresh', identities_path(:user_types => @selected_users)

- @users.each do |user|
  %p
    %table{:class => "appt"}
      %tr
        %td{:width => "60%"}
          %p
            Name: #{user.name} <br/>
            Email: #{user.email} <br/> 
        %td{:width => "40%"}
          %p 
          =button_to "Delete", "/users/#{user.uid}", :method => :delete, :confirm => 'Are you sure?'

= will_paginate @users

app/views/identities/new.html.erb
<!-- <div id="calendar">
 --> 
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
</script>
<script>
var rank;

  var pw = "";
  var possibilities = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789?.!^$#@><+=_,/;:";
  for (var i = 0; i < 10; i++) {
    pw += possibilities.charAt(Math.floor(Math.random()*possibilities.length));
  }

var alertFunction = function() {
  alert("Don't lose the following password: " + pw + "\n It might take a while for the page to redirect; please be patient!");
}


$(document).ready(function(){

  $("#name_form").hide();
  $("#email_form").hide();
  $(".password_form").hide();
  $("#password").attr("value", pw);
  $("#password_confirmation").attr("value", pw);
  $("#name").attr("value", "default");
  $("#email").attr("value", "c@citadel.com");

  $("select").change(function(){
     rank = $("select").find(":selected").html();
     if (rank == "participant"){ 
       $("#name_form").slideUp(0);
       $("#email_form").slideUp(0);
       $("#school_form").slideDown(0);
       $("#number_form").slideDown(0);
       //$("#password").attr("value", pw);
       //$("#password_confirmation").attr("value", pw);
       $("#name").attr("value", "default");
       $("#email").attr("value", "c@fueled.com");
     }else if (rank == "admin"){
       $("#name_form").slideDown(0);
       $("#email_form").slideDown(0);
       $("#school_form").slideUp(0);
       $("#number_form").slideUp(0);
       //$("#password").attr("value", "");
       //$("#password_confirmation").attr("value", "");
       $("#name").attr("value", "");
       $("#email").attr("value", "");
      } else if (rank == "counselor"){
       $("#name_form").slideDown(0);
       $("#email_form").slideDown(0);
       $("#school_form").slideUp(0);
       $("#number_form").slideUp(0);
       //$("#password").attr("value", pw);
       //$("#password_confirmation").attr("value", pw);
       $("#name").attr("value", "");
       $("#email").attr("value", "");
      }
  });
});
</script>
 <div class = "mainContentBox">
  <div class = "mainContentBoxHeader">New Admin/Student Account</div>

  Please fill in the blanks below with the correct information. <br> <br>

  <%= form_tag "/auth/identity/register" do %>
    <% if @identity && @identity.errors.any? %>
      <div class="error_messages">
        <h2><%= pluralize(@identity.errors.count, "error") %> prohibited this account from being saved:</h2>
        <ul>
        <% @identity.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <nav>
      <table cellpadding="5px", width: "100%" class="textbox">
            <tr>
              <td><%= label_tag :rank %></td>
              <td><%= select_tag :rank, options_for_select(User::USER_TYPES)%>
            </td>
        </tr>
            <tr id="name_form">
              <td><%= label_tag :name %></td>
              <td><%= text_field_tag :name, @identity.try(:name) %></td>
            </tr>


            <tr id="email_form">
              <td><%= label_tag :email %></td>
              <td><%= text_field_tag :email, @identity.try(:email) %></td>
            </tr>
            <tr class="password_form">
              <td><%= label_tag :password %></td>
              <td><%= password_field_tag :password %></td>
            </tr>
            <tr class="password_form">
              <td><%= label_tag :password_confirmation %></td>
              <td><%= password_field_tag :password_confirmation %></td>
            </tr>

   

      </table>

    </nav>
      <div class="actions">
        <input class = "button" name="commit" type="submit" value="Register" onClick="alertFunction()">
      </div>
  <% end %>

app/views/identities/show.html.haml
-#  This file is app/views/users/show.html.haml

%div{:class => "mainContentBox"}
  .mainContentBoxHeader #{@user.name}'s Profile
  %p
    %b Name:
    #{@user.name}
  %p
    %strong Email:
    #{@user.email}
  %p
    %strong Created At:
    #{@user.created_at}
  %p
    %strong User ID:
    #{@user.uid}

  / -if (!current_user.nil? && current_user.uid == @user.uid) or (current_user.rank == "admin")
  /   =link_to "Edit Profile", "/users/#{@user.uid}/edit", :class => "appt"
  /   =button_to "Delete", user_path(@user), :method => :delete, :confirm => 'Are you sure?'