config/routes.rb
MathLab::Application.routes.draw do
  get "login/index"
  get "index/index"

  root :to => redirect('/login/index')
  resources :users
  resources :sessions

  match "/appointments/past" => "appointments#past", :as => :past, via: :get
  match "/reports/export" => "reports#export", :as => :export, via: :get
  match "/user/:id/add_school" => "users#add_school", as: :add_school, via: :get
  match "/h9Hbbe894xx030" => "reset#index", as: :reset, via: :get
  match "/h9Hbbe894xx030/execute" => "reset#execute", as: :reset_execute, via: :put

  resources :appointments
  resources :schools

  match "/auth/:provider/callback" => "sessions#create", via: :post
  match "/auth/identity/register" => "identities#new", via: :post
  match "/auth/failure" => "sessions#failure", via: :get
  match "/signout" => "sessions#destroy", :as => :signout, via: :get
  match "/change_password" => "users#change_password", :as=> :change_password, via: :get

  scope '/admins' do
    resources :identities
    resources :schools
    resources :reports
  end

  resources :identities
  resources :admins
 

  

end

app/views/layouts/admin.html.haml
!!! 5
%html
  %head
    %title Math Lab
    = stylesheet_link_tag 'application'
    = csrf_meta_tags

  %body
  -if !@current_user.nil?

    %div#main
      %div{:id => "header-main", :class => "header"}
        %div{:id => "title"}
          %h1.inline
            =image_tag "citadel_military_logo.jpg", :height => "100px"
          %h3.inline Admin Portal

        %nav
          -if !@current_user.nil?
            %ul
              %li=link_to "Home", "/admins", :class => "button-square"
              
              %li=link_to "Signout", "/signout", :class => "button-square"

        %div.clear

      %div{:id => "content"}

        %div{:id => "sidebar"}
          %div{:class => "button-pink", :id => "appointment"}
            %h3=link_to "View & Create Accounts", "/admins/identities"
          %div{:class => "button-pink", :id => "appointment"}
            
            %h3=link_to "Reports", "/admins/reports"
          / %div{:class => "button-pink", :id => "appointment"}
          /  %h3=link_to "Reports", "/admins"
          %div{:id => "user_info"}
            %h2 My Information
            %p.textbox 
              Name: #{@current_user.name} <br/>
              Rank: #{@current_user.rank} <br/><br/>
              =link_to "Change password", "/change_password", :class => "link"

        %div{:id => "calendar"}

          - if flash[:notice]
            #notice.message= flash[:notice]
          - elsif flash[:warning]
            #warning.message= flash[:warning]

          = yield

        %div.clear
        %div{:id => "footer"}
  -else
    = yield

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Math Lab
    = stylesheet_link_tag 'application'
    = csrf_meta_tags

  %body
  -if !@current_user.nil?

    %div#main
      %div{:id => "header-main", :class => "header"}
        %div{:id => "title"}
          %h1.inline
            %a{:href => "/"}
              =image_tag "citadel_military_logo.jpg", :height => "100px"
          %h3.inline
            if @current_user.rank == "participant" || @current_user.rank == "client"
              PARTICIPANT PORTAL
            -else
              ADMIN PORTAL

        %nav
          -if !@current_user.nil?
            %ul
              -if @current_user.rank == "admin"
                %li=link_to "home", "/admins", :class => "button-square"
                %li=link_to "schools", "/admins/schools", :class => "button-square"
              -else
                -if @current_user.rank == "counselor" || @current_user.rank == "intern"
                  %li=link_to "profile", "/users/#{@current_user.uid}", :class => "button-square"
                %li=link_to "scheduler", "/appointments", :class => "button-square"
              %li=link_to "signout", "/signout", :class => "button-square"

        %div.clear

      %div{:id => "content"}

        %div{:id => "sidebar"}
          -if @current_user.rank == "counselor" || @current_user.rank == "intern"
            %div{:class => "button-pink", :id => "appointment"}
              %h3=link_to "Create Appointment Slots", "/appointments/new"
          %div{:id => "user_info"}
            %h2 my information
            %p.textbox 
              Name: #{@current_user.name} <br/>
              Rank: #{@current_user.rank} <br/><br/>
              =link_to "Change password", change_password_path, :class => "link"
              -if @current_user.rank != "admin"
           
         

          - if flash[:notice]
            #notice.message= flash[:notice]
          - elsif flash[:warning]
            #warning.message= flash[:warning]

          = yield

        %div.clear
        %div{:id => "footer"}
  -else
    = yield
	

app/views/layouts/application2.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Math Lab</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>